import React from "react";
import DefaultLayout from "./components/layout/Layout";
import ClearFixed from "./components/ClearFixed";

const ProductCollectionPage = () => {
    return <DefaultLayout fixedHeader={true}>
        <ClearFixed />
        <h1>ProductCollectionPage</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. A asperiores minus unde, ullam numquam temporibus consectetur corporis earum architecto itaque ipsa iure ipsam cumque tempora magni laudantium deleniti est ipsum.</p>
    </DefaultLayout>;
}
export default ProductCollectionPage;